M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu20.04.1} date Wed 18 Jan 2023 09:44:46 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-18T21:44:46-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X6.8545Y-4.8256
X7.0455Y-4.8256
T2
X6.8427Y-4.9449
X7.0573Y-4.9449
T0
M30
