M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu20.04.1} date Sat 31 Dec 2022 05:49:30 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-31T17:49:30-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1063
%
G90
G05
T1
X4.8565Y-3.9045
X4.8565Y-4.0955
T2
X4.7372Y-3.8927
X4.7372Y-4.1073
T3
X7.23Y-3.075
X7.23Y-4.925
T0
M30
