M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu20.04.1} date Fri 30 Dec 2022 06:50:20 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-30T18:50:20-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1063
%
G90
G05
T1
X4.9835Y-3.9045
X4.9835Y-4.0955
T2
X4.8642Y-3.8927
X4.8642Y-4.1073
T3
X7.26Y-3.075
X7.26Y-4.925
T0
M30
